name: salam_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Updated to common range constraint based on ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Original Dependencies (cleaned)
  intl: ^0.18.1 # Needed for reminder feature date formatting too
  image_picker: ^1.1.2 # Kept latest version specified
  file_picker: ^5.3.3
  video_player: ^2.8.2
  chewie: ^1.8.1
  google_fonts: ^6.2.1
  audioplayers: ^6.4.0 # Changed to caret syntax for flexibility
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  dotted_line: ^3.2.3
  cached_network_image: ^3.4.1
  mask_text_input_formatter: ^2.9.0

  shared_preferences: ^2.5.2

  # State Management (Note: Both Riverpod and Provider are now listed)
  flutter_riverpod: ^2.6.1 # Your existing state management
  provider: ^6.1.2 # Added for the provided reminder feature code

  # New Dependencies for Reminder Feature
  uuid: ^4.4.0 # For unique reminder IDs
  flutter_slidable: ^3.1.0 # For swipe-to-remove functionality


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # The "flutter_lints" package below contains a set of recommended lints to
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0 # Updated to a more recent version, adjust if needed

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # Declaring folders includes all files within them.
  assets:
    - assets/images/
    - assets/videos/
    - assets/sounds/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package