// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy6Sal-PxA8D2Xmyir2NSxzxluOPv7a8I',
    appId: '1:146175145457:web:ade376aa7de9cbe4cfc050',
    messagingSenderId: '146175145457',
    projectId: 'my-psut-flutter-project',
    authDomain: 'my-psut-flutter-project.firebaseapp.com',
    storageBucket: 'my-psut-flutter-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMuMyX1lco7IXfYseguKdb6-EfNUB0V00',
    appId: '1:146175145457:android:225c8bf76515e1cdcfc050',
    messagingSenderId: '146175145457',
    projectId: 'my-psut-flutter-project',
    storageBucket: 'my-psut-flutter-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu-DqulCVs16JUUU_hZhtTqgJFJf_RVLk',
    appId: '1:146175145457:ios:042916ac1cad69c3cfc050',
    messagingSenderId: '146175145457',
    projectId: 'my-psut-flutter-project',
    storageBucket: 'my-psut-flutter-project.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu-DqulCVs16JUUU_hZhtTqgJFJf_RVLk',
    appId: '1:146175145457:ios:042916ac1cad69c3cfc050',
    messagingSenderId: '146175145457',
    projectId: 'my-psut-flutter-project',
    storageBucket: 'my-psut-flutter-project.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy6Sal-PxA8D2Xmyir2NSxzxluOPv7a8I',
    appId: '1:146175145457:web:42f2cfad54f2bca5cfc050',
    messagingSenderId: '146175145457',
    projectId: 'my-psut-flutter-project',
    authDomain: 'my-psut-flutter-project.firebaseapp.com',
    storageBucket: 'my-psut-flutter-project.firebasestorage.app',
  );
}
